### ISSUE TITLE
Remove Wasm code from rust API published on crates.io

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_emit#33]
We need to separate out the Wasm code (js_sys/wasm_bindgen stuff) from the rest of the rust types in the API we publish on crates.io. This will allow us to consume this crate in the CLI and provide an API for people to use with Rust.

**Comment by ProofOfKeags** [comment]
So I guess I have a few questions here.

1. Is the wasm code needing to be *removed* from this crate entirely? or *just* separated and given feature flags?
2. how deep does wasm "infect" this codebase? Is it at the edges whilst code generating or is it deeply embedded into the bundling code already?
3. Assuming the APIs should appear for both wasm *and* rust, should it be the same APIs or should they vary slightly since the consumers will be fundamentally different environments?

**Comment by dsherret** [comment]
It's a bit of a large refactor and a lot to explain. I will put up a PR in a few minutes
