### ISSUE TITLE
emit() should allow importMaps

### ISSUE THREAD

**Issue by peetklecha** [denoland/deno_emit#67]
Apparently support for importMaps was removed from `emit()` -- I'm not sure why. Ideally `emit()` would (at least optionally) take an importMap and translate imports accordingly. However, if that's difficult or undesirable for any reason, at the least it would be really nice for it to just (again, at least optionally) ignore import strings like "react" and leave them untouched rather than breaking on them.

**Comment by kitsonk** [comment]
It was to get it out the door, not long term intentional.  The underpinnings in Rust still support import maps, but it isn't exposed.

**Comment by peetklecha** [comment]
gotcha, that's great to hear. do you have any sense what the timeline might be for getting them back?

**Comment by lowlighter** [comment]
Also interested in knowing if there's any approximative ETA for this too, since it prevents moving out from v1.21

**Comment by lowlighter** [comment]
> It was to get it out the door, not long term intentional. The underpinnings in Rust still support import maps, but it isn't exposed.

Any links/references/leads to if someone would like to open a PR for this ?

**Comment by yacinehmito** [comment]
> The underpinnings in Rust still support import maps, but it isn't exposed.

The [implementation of the CLI](https://github.com/denoland/deno/blob/2f7222da8a26d8be915b9467fc21649a18f54b77/cli/resolver.rs#L114) seems to suggest that import map resolution is part of `deno` and not `deno_graph`. Should that be reimplemented in `deno_emit` or pushed down to `deno_graph`?

**Comment by cowboyd** [comment]
@kitsonk If someone could provide a sketch of an implementation plan, I think there are lots of folks willing to take a stab at this issue.

**Comment by yacinehmito** [comment]
Kitson Kelly is not working at Deno Land anymore. Paging @bartlomieju instead.

**Comment by yacinehmito** [comment]
I am currently working on this.

> The [implementation of the CLI](https://github.com/denoland/deno/blob/2f7222da8a26d8be915b9467fc21649a18f54b77/cli/resolver.rs#L114) seems to suggest that import map resolution is part of deno and not deno_graph. Should that be reimplemented in deno_emit or pushed down to deno_graph?

I saw that it was by design that `deno_graph` didn't embed the import map logic. Instead it expects a customer resolver that peforms the import map resolution, which in turn would rely on the `import_map` create. So, we have to reproduce the logic from the deno CLI in `deno_emit`, until there is either:
- An agreement that this logic should be in `deno_graph`
- An other layer abstraction that both the deno CLI and `deno_emit` would tap into.

I have something going but I am hitting a blocker: import maps expect a base URL as an import map can (and often does) contain relative paths. However I don't see any existing option or heuristic to derive the base URL from the input of `bundle()`. Shall I add another option to provide the base URL? Shall that option be tied to import maps, or generic — assuming that other future behavior would depend on such base URL? Shall the option have a default value, and if so, how would that be derived?

I can get to something that works but I'd like some design guidance.
