### ISSUE TITLE
Migrate shebang fix from the Deno repo to here

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_emit#85]
https://github.com/denoland/deno/pull/17113/files

**Comment by yacinehmito** [comment]
It took me a while to understand why the Rust unit test was passing but not the JS one.

The fix seems works Rust-side but not JS side because the default loader is the one from `deno_cache`, and `deno_cache` strips the shebang when loading, [as seen in the code](https://github.com/denoland/deno_cache/blob/e1102adf1ea44d1fab9e13d315d08e2d424e72e9/file_fetcher.ts#L79). 

What is the usefulness of stripping the shebang in `deno_cache`? Is it something that can be remove, or at least made configurable?
